version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./apps/backend:/app
    env_file:
      - .env

  # frontend:
  #   build:
  #     context: .
  #     dockerfile: docker/frontend.Dockerfile
  #   ports:
  #     - "5173:5173"
  #   volumes:
  #     - ./apps/frontend:/app
  #   env_file:
  #     - .env
