services:
  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    volumes:
      - ./apps/backend/prisma:/app/prisma

  frontend:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    ports:
      - "0.0.0.0:5173:5173"
    env_file:
      - .env
    depends_on:
      - backend
